services:
  mhl-homes-web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Aquí pones la URL real de tu backend en AWS
        - EXPO_PUBLIC_API_URL=https://mhlhomes.ddns.net
    ports:
      - "8081:80"   # Puerto estándar HTTP
      - "8081:443" # Si usas HTTPS
    restart: always